/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


@interface thriftServiceResponseObj : NSObject <TBase, NSCoding> {
  NSString * __msg;
  BOOL __status;

  BOOL __msg_isset;
  BOOL __status_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, getter=status, setter=setStatus:) BOOL status;
#endif

- (id) init;
- (id) initWithMsg: (NSString *) msg status: (BOOL) status;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (BOOL) status;
- (void) setStatus: (BOOL) status;
#endif
- (BOOL) statusIsSet;

@end

@protocol thriftServiceChatTransport <NSObject>
- (NSString *) getToken: (NSString *) accessToken;  // throws TException
- (thriftServiceResponseObj *) sendVideo: (int32_t) appCredentialId token: (NSString *) token socketResponse: (NSString *) socketResponse bufferedByte: (NSData *) bufferedByte fileName: (NSString *) fileName;  // throws TException
- (thriftServiceResponseObj *) sendPicture: (int32_t) appCredentialId token: (NSString *) token socketResponse: (NSString *) socketResponse bufferedByte: (NSData *) bufferedByte fileName: (NSString *) fileName;  // throws TException
- (thriftServiceResponseObj *) sendPrivatePhoto: (int32_t) appCredentialId token: (NSString *) token socketResponse: (NSString *) socketResponse bufferedByte: (NSData *) bufferedByte fileName: (NSString *) fileName;  // throws TException
- (thriftServiceResponseObj *) sendVoice: (int32_t) appCredentialId token: (NSString *) token socketResponse: (NSString *) socketResponse bufferedByte: (NSData *) bufferedByte fileName: (NSString *) fileName;  // throws TException
- (thriftServiceResponseObj *) expireMyToken: (int32_t) appCredentialId token: (NSString *) token;  // throws TException
- (NSData *) getVideo: (int32_t) appCredentialId token: (NSString *) token id: (int32_t) id;  // throws TException
@end

@interface thriftServiceChatTransportClient : TBaseClient <thriftServiceChatTransport> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface thriftServiceChatTransportProcessor : NSObject <TProcessor> {
  id <thriftServiceChatTransport> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithChatTransport: (id <thriftServiceChatTransport>) service;
- (id<thriftServiceChatTransport>) service;
@end

@interface thriftServiceChatTransportConstants : NSObject {
}
@end
